<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="USHYDKDARISI02" name="TestKanya1" tests="3" failures="2" timestamp="25 Oct 2022 11:13:18 GMT" time="84.124" errors="0">
  <testcase name="step01" time="25.59" classname="sample.StandaloneProjectDuplicate"/>
  <testcase name="step02" time="5.305" classname="sample.StandaloneProjectDuplicate">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
	at sample.StandaloneProjectDuplicate.step02(StandaloneProjectDuplicate.java:116)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- step02 -->
  <testcase name="step02" time="5.294" classname="sample.StandaloneProjectDuplicate">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
	at sample.StandaloneProjectDuplicate.step02(StandaloneProjectDuplicate.java:116)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- step02 -->
</testsuite> <!-- TestKanya1 -->
